### PR TITLE
Explorer markup, styles refactoring

### PR DESCRIPTION
**Pull request by vslstasiuk**
In this PR:
-  Explorer and all related pages markup
- Migrating to Tailwind instead of Styled-components&Mantine
- UI-kit
- refactoring of main layout and basic components (Header, Footer, MobileMenu)

### CODE REVIEW

**Comment by dblackstone1** [comment]
Screenshot 2024-05-01 at 3 22 22 PM
Screenshot 2024-05-01 at 3 22 31 PM
Screenshot 2024-05-01 at 3 22 43 PM
Screenshot 2024-05-01 at 3 23 05 PM

Fixes to the coloring in these would be good

**Comment by dblackstone1** [comment]
Will need to add pages for the block view and transaction view after this

**Review by dblackstone1 — CHANGES_REQUESTED** [review]
see comments (with screenshots of the areas)

**Comment by dblackstone1** [comment]
Screenshot 2024-05-01 at 3 26 10 PM

Should one or both of these return to the landing page?

**Comment by vslstasiuk** [comment]
1) I'm not sure what the reason of it, but in my browser it is with correct colors. Maybe it depends on theme installed in chrome. I'm fixing it
2) They are ready, maybe i missed to add demo links in lists, i'll add them (/explorer/transactions/:id and /explorer/blocks/:id routes)
3) the logo returns to the main page, but it use link from .env file. I've added .env.example with url to localhost (VITE_PUBLIC_APP_URL=http://localhost:5173/), but at prod it should be added with correct domain)

**Review by dblackstone1 — APPROVED** [review]

**Pull request merged**
