### PR TITLE
Add X1NODE with testnet-focused description, logo, guides, snapshots,…

### PR DESCRIPTION
**Pull request by xonerafa**
## X1NODE - Testnet Validator

**Description:**
X1NODE provides reliable validation services on the testnet with robust infrastructure and constant monitoring. We’re committed to network security and decentralization.

**Key Information:**
- **Infrastructure:** High-performance servers
- **Support:** [Setup Guide](https://docs.x1node.xyz) | [Testnet Snapshot](https://docs.x1node.xyz/snapshots) | [Genesis File](https://docs.x1node.xyz/genesis-files)

Partner with X1NODE for reliable testnet validation!

### CODE REVIEW

**Review by dblackstone1 — CHANGES_REQUESTED** [review]
these are not in our formats.  i added the image and trusted companies section, but check the validator pages, as those have many more changes.  split this amongst those files

**Comment by dblackstone1** [comment]
also pull latest from main

**Comment by xonerafa** [comment]
"I have completed all the requested changes. Please review and let me know if there is anything else that needs to be fixed. Thank you!"

**Comment by dblackstone1** [comment]
copied it over myself.  closing this

**Pull request closed without merging**
